; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "inventory_pos"
; Passed in by build_installer.ps1, which reads it from pubspec.yaml. The fallback exists only so
; the script still compiles when opened by hand in the Inno Setup IDE.
;
; It was hardcoded to "1.0", which meant every build ever produced announced the same version — so
; a till could not be told whether it had the new one, which is the entire point of shipping it.
#ifndef MyAppVersion
  #define MyAppVersion "0.0.0-local"
#endif
#define MyAppPublisher "Bridge77 Technologies"
; Feeds AppPublisherURL, AppSupportURL and AppUpdatesURL below — the links a shopkeeper
; sees on the installer's pages and in Add/Remove Programs. Cosmetic: nothing in the
; update mechanism reads it. The till finds updates through the pointer in
; lib/core/update/update_endpoints.dart, which is a GitHub address and entirely separate.
;
; Checked live before being written here, because a publisher link that 404s in
; Add/Remove Programs is worse than no link at all, and this one goes into a signed
; binary that then sits on a till for years.
;
; Two things about it are easy to get wrong, and both were got wrong once already:
;
;   www.bridge77.vercel.app   Fails TLS. Vercel's certificate covers *.vercel.app, a
;                             single label, so it does not match a name two deep. The
;                             connection is refused before any page is requested — a
;                             security warning rather than a 404. Do not re-add the www.
;   /products/proxypos        404. The path is case-sensitive; it is ProxyPos.
;
; The site is also moving under this: /products answered 200 and /products/ProxyPos 404
; earlier the same day, and they have since swapped. Verified 200 at the moment of
; writing, which is all anyone can do — if this link is reported dead later, that is why,
; and the root (https://bridge77.vercel.app/) is the steadier choice.
;
; Previously https://www.fasahahaus.com/, the former company.
;
; Worth knowing when this is next touched: a vercel.app address is a host's subdomain,
; not a domain under this company's control, so it goes away when the hosting does.
; Harmless here in a way it would not be for the update pointer — a dead link in
; Add/Remove Programs is untidy, a dead update address strands a till.
#define MyAppURL "https://bridge77.vercel.app/products/ProxyPos"
#define MyAppExeName "inventory_app_pos.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
; Where `flutter build windows --release` puts its output, relative to this script.
#define BuildDir SourcePath + "..\\build\\windows\\x64\\runner\\Release"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{F3765B58-4AE4-472C-B625-9CE52DD33C29}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
; Relative to this file. Every path here pointed at C:\Users\f.dankwah\..., so the installer
; could only be built on one machine with the project at one exact location.
OutputDir=.
; Versioned, so two installers sitting in a folder can be told apart — which is the difference
; between "this till has the fix" and "this till has an installer".
OutputBaseFilename=inventory_pos-{#MyAppVersion}
SetupIconFile={#SourcePath}..\windows\runner\resources\app_icon.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; One recursive line rather than a hand-kept list of DLLs.
;
; The list named five plugin DLLs explicitly, so adding a plugin shipped an installer missing its
; DLL — an app that installs cleanly and then fails at startup on a machine nobody is watching.
; Flutter puts everything the app needs in the Release folder, so ship the Release folder.
Source: "{#BuildDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; `skipifsilent` was here and has been removed deliberately.
;
; An auto-update runs this installer with /SILENT. With skipifsilent the till would
; install the new version and then sit there switched off, on a counter, with a queue
; in front of it — waiting for somebody to notice and double-click the icon. The whole
; point of the update is that the shopkeeper agrees to it once and the till comes back.
;
; The cost is that a scripted /VERYSILENT deployment also launches the app. For a
; point-of-sale terminal that is the behaviour you want anyway.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall

